---
title: ""
output: pdf_document

---

```{r include=FALSE}
options(repos="https://cran.rstudio.com" )

install.packages(c('ggplot2', 'dplyr', 'grid', 'gridExtra', 'tidyr', 'glue'))
library(ggplot2)
library(dplyr)
library(grid) 
library(gridExtra)
library(tidyr)
library(glue)

# Change the number for each knit to obtain each student's report.
s = 1

#You don't have to pull in the data again ONLY IF it is already in your global environment. And here we need the Combined Data National file.
dat.long <- read.csv('C:/Users/dal362/OneDrive - Drexel University/Desktop/Exec Ed/MERCK Diverse Supplier/CombinedDataNational.csv')

# Separate scores from ranges
# This will insert NAs into the cohort range
dat.long <- dat.long %>% 
  separate(Score, into = c("Score", "range"), sep = " ") %>% 
  mutate(Score = as.numeric(Score))

# Remove NAs from cohort range and replace with blank space
# This ensures 'NA' doesn't print on the bar chart
dat.long$range[is.na(dat.long$range)] <- ' '

```


Attitude and Motivation Towards Leading

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>%
  filter(ScaleID == paste0('MOTAI', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('MOTSN', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('MOTNC', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('LEff', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

```




Leadership Abilities




```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}


dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>%
  filter(ScaleID == paste0('MOTI', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'Cohort (Peer) Average Rating')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('SI', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'Cohort (Peer) Average Rating')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) + 
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('MCON', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'Cohort (Peer) Average Rating')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('WIT', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'Cohort (Peer) Average Rating')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

```

#^Dark blue and green should always have ranges. The teal and yellow never should. 

Empowering Leadership
 
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}


dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>%
  filter(ScaleID == paste0('LBE', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('PDM', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) + 
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('COACH', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('INF', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) + 
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('SCTI', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))



```

Visionary & Meaning-Based Leadership

```{r}

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('VL', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'Cohort (Peer) Average Rating')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('MBL', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'Cohort (Peer) Average Rating')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

```



Knowledge Sharing


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('SAFE', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.04, y=Score+.1), width=3, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'National Average')), values=c('#58a7ea', '#65efdb', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('ITT', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('KS', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.04, y=Score+.1), width=3, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'National Average')), values=c('#58a7ea', '#65efdb', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('IE', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

```

Political Skills

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('NET', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('II', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('SAS', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
 geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('ASN', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

```





Attitudes Towards Others

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}


dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('COOP', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'Cohort (Peer) Average Rating')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))


```



  Teaming Approach and Skills
  

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}


dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('TMX', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'Cohort (Peer) Average Rating')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 4, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))


dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('SL', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))


dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('CRE', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.56, y=Score+.1), width=4, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'Average Peer Rating', 'National Average')), values=c('#58a7ea', '#65efdb', '#64CA55', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

```


Resistance to Change


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('RTCRS', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.04, y=Score+.1), width=3, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'National Average')), values=c('#58a7ea', '#65efdb', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 3, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))
        
dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('RTCER', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.04, y=Score+.1), width=3, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'National Average')), values=c('#58a7ea', '#65efdb', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 3, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))
        


```




Attitudes



```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('PT', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.04, y=Score+.1), width=3, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'National Average')), values=c('#58a7ea', '#65efdb', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 3, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('PP', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=2.04, y=Score+.1), width=3, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score', 'National Average')), values=c('#58a7ea', '#65efdb', '#EFCD5B')) +
  guides(fill = guide_legend(nrow = 3, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=7, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))


```




EI

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('EISE', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) +
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('EIOE', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) +
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('EIUE', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) +
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('EIRE', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) +
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

```

Values

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>%
  filter(ScaleID == paste0('ALT', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('PAY', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('REL', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('SEC', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

```

Values page 2

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>%
  filter(ScaleID == paste0('AUTH', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('VAR', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('AUTO', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

dat.long %>% 
  mutate(label = glue("{Score} {range}")) %>% 
  filter(ScaleID == paste0('PRES', s)) %>%
  ggplot(aes(x=Scale, y=Score)) + 
  geom_bar(aes(x=1.54, y=Score+.23), width=2, fill='#cccccc', alpha=.5, stat='identity', position='dodge2') +
  geom_bar(aes(x=Scale, y=Score, fill=Scale), stat = 'identity', width=.9, alpha=1, position='dodge') +
  ggtitle(label='') +
  scale_y_continuous(breaks=seq(1, 7, 1), limits = c(0, 7), expand=c(0,0)) +  
  scale_x_discrete(labels=element_blank()) +    
  scale_fill_manual(label=paste0(c('Your Score', 'Cohort Score')), values=c('#58a7ea', '#65efdb')) + 
  guides(fill = guide_legend(nrow = 2, reverse = F)) +
  geom_text(aes(x=Scale, label=label, y=1.5), size=8, color='#000000') +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(size=10),
        panel.background = element_rect(fill = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "#666666", linetype='dotted'),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.position = 'none',
        legend.title = element_blank(),
        axis.line.x = element_line(color='#333333', size=0.5), 
        axis.line.y = element_line(color='#333333', size=0.5),
        axis.title = element_blank(),    
        axis.text = element_text(size=17),
        axis.ticks.length=unit(0, 'cm'))

```